name: 'Maven Parent Updater Action'
description: 'This action allows to sync the version of a Maven Root POM with the current version on Maven Central'
author: 'Sebastian Krach'
inputs:
  root_pom_filename:
    required: false
    description: 'the file name of the root pom of the project'
    default: 'pom.xml'
  maven_repository:
    required: false
    description: 'The Base URL of the Maven repository to check the latest release version of the parent pom'
    default: 'https://repo1.maven.org/maven2/'
runs:
  using: 'node12'
  main: 'dist/index.js'
